[technote]
id = "SQR-084"
series_id = "SQR"
canonical_url = "https://sqr-084.lsst.io"
github_url = "https://github.com/lsst-sqre/sqr-084"
github_default_branch = "main"
date_created = 2024-01-25T20:05:52Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

# [technote.status]
# state = "draft"

[technote.sphinx]
extensions = ["sphinx_design"]

[[technote.authors]]
name.given = "Frossie"
name.family = "Economou"
internal_id = "economouf"
orcid = "https://orcid.org/0000-0002-8333-7615"
[[technote.authors.affiliations]]
name = "Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ  85719, USA"
[[technote.authors]]
name = {given = "Jonathan", family = "Sick"}
internal_id = "sickj"
orcid = "https://orcid.org/0000-0003-3001-676X"
[[technote.authors.affiliations]]
name = "Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"
